<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>SteamSync.PlayniteWorker</RootNamespace>
    <AssemblyName>SteamSync.PlayniteWorker</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PlayniteSDK" Version="6.14.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteamSync.PlayniteAdapter\SteamSync.PlayniteAdapter.csproj" />
  </ItemGroup>

</Project>
